version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: que-ts-postgres
    environment:
      POSTGRES_DB: que_test
      POSTGRES_USER: que_user
      POSTGRES_PASSWORD: que_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./docker/init-test-db.sql:/docker-entrypoint-initdb.d/02-init-test-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U que_user -d que_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
